
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WallBounce iOS' do
  pod 'Mixpanel'
end

target 'WallBounce Android' do

end

target 'WallBounce Mac' do

end
